version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=caonam
      - POSTGRES_PASSWORD=namnam

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: caonam@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: namnam
